# Publishing extensions to VS Marketplace using SP

trigger:
  - main

jobs:
- job: publish_vsix
  displayName: Publish VSIX
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: TfxInstaller@4
    inputs:
      version: 'v0.x'
      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        npm i azure-devops-extension-sdk
        npm install vss-web-extension-sdk
  
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'IDC Special Clouds (Test)(6e007163-28ab-48d9-af19-4382829fabb8)'
      KeyVaultName: 'SPSec'
      SecretsFilter: 'PipelineSpSecret, SP-Client-ID'
      RunAsPreJob: false

  # - task: GetSPUserID@1
  #   inputs:
  #     TenantID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
  #   env:
  #     CLIENT_SECRET: $(PipelineSpSecret)
  #     CLIENT_ID: $(SP-Client-ID)

  - task: PublishVSExtensionUsingSP@1
    inputs:
      TenantID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      ManifestFile: 'vss-extension.json'
    env:
      CLIENT_SECRET: $(PipelineSpSecret)
      CLIENT_ID: $(SP-Client-ID)