# Publishing extensions to VS Marketplace using SP

trigger:
  - main

jobs:
- job: just_vsix
  displayName: Publish VSIX
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: TfxInstaller@4
    inputs:
      version: 'v0.x'
      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Installing required npm packages
        
        npm i azure-devops-extension-sdk
        npm install vss-web-extension-sdk
  
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'IDC Special Clouds (Test)(6e007163-28ab-48d9-af19-4382829fabb8)'
      KeyVaultName: 'SPSec'
      SecretsFilter: 'PipelineSpSecret'
      RunAsPreJob: false
      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Logging in with a service principal"
        
        # az login --service-principal --tenant <tenant-id> --username <app-id> --password <password-or-cert>
        
        az login  --allow-no-subscriptions --service-principal --tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 --username f0df0d20-3823-4657-87b1-3082030e2006 --password $(PipelineSpSecret)
        
        Write-Host "Obtain access token for Service Principal"
        
        $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
        
        $Response = Get-Content ".\vss-extension.json"

        $ResponseObject = $Response | ConvertFrom-Json

        tfx extension publish --publisher $ResponseObject.publisher --auth-type pat -t $accessToken
    