# Sample pipeline to show GetSPUserID custom task

jobs:
- job: User_ID_SP
  displayName: User ID of SP
  pool:
    vmImage: 'windows-latest'
  steps:
  
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'IDC Special Clouds (Test)(6e007163-28ab-48d9-af19-4382829fabb8)'
      KeyVaultName: 'SPSec'
      SecretsFilter: 'PipelineSpSecret, SP-Client-ID'
      RunAsPreJob: false

  - task: GetSPUserID@1
    inputs:
      TenantID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
    env:
      CLIENT_SECRET: $(PipelineSpSecret)
      CLIENT_ID: $(SP-Client-ID)