# Publishing extensions to VS Marketplace using SP

trigger:
  - main

jobs:
- job: build_vsix
  displayName: Building VSIX
  pool:
    vmImage: "windows-latest"
  steps:
  - task: PackageAzureDevOpsExtension@4
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)'
      updateTasksVersion: false

- job: publish_artificat
  displayName: Publishing artificat
  pool:
    vmImage: "windows-latest"
  dependsOn: build_vsix
  steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/*.vsix
        artifactName: extension
    