# Publishing extensions to VS Marketplace using SP

trigger:
  - main

jobs:
- job: publish_vsix
  displayName: Publish VSIX
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: TfxInstaller@4
    inputs:
      version: 'v0.x'
  
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'IDC Special Clouds (Test)(6e007163-28ab-48d9-af19-4382829fabb8)'
      KeyVaultName: 'SPSec'
      SecretsFilter: 'PipelineSpSecret, SP-Client-ID'
      RunAsPreJob: false

  